---
apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.1.0
    init: confluentinc/confluent-init-container:2.3.0
  configOverrides:
    jvm:
      - "-XX:+HeapDumpOnOutOfMemoryError"
      - "-XX:HeapDumpPath=/mnt/data/data0/head_dump.hprof"
      - "-XX:+UseG1GC"
      - "-Xmx8000M"
      - "-Xms5500M"
  dataVolumeCapacity: 50Gi
  logVolumeCapacity: 50Gi
  storageClass:
    name: cflt-storage
  podTemplate:
    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
      limits:
        cpu: "3"
        memory: "10Gi"