---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.1.0
    init: confluentinc/confluent-init-container:2.3.0
  configOverrides:
    server:
      - confluent.metrics.reporter.topic.retention.ms=86400000
      - confluent.metrics.reporter.topic.retention.bytes=522752000
      - confluent.controlcenter.internal.topics.retention.ms=86400000 
    jvm:
      - "-XX:+HeapDumpOnOutOfMemoryError"
      - "-XX:HeapDumpPath=/mnt/data/data0/head_dump.hprof"
      - "-XX:+UseG1GC"
      - "-Xmx16000M"
      - "-Xms8000M"
  dataVolumeCapacity: 250Gi
  storageClass:
    name: cflt-storage
  podTemplate:
    resources:
      requests:
        cpu: "4"
        memory: "16Gi"
      limits:
        cpu: "8"
        memory: "20Gi"
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    ksqldb:
    - name: ksqldb
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url: http://connect.confluent.svc.cluster.local:8083
  externalAccess:
    type: loadBalancer
    loadBalancer:
       domain: confluent.svc.cluster.local